version: '3.7'

services:
  account-manager-service:
    container_name: validator-service
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - adex-network
networks:
  adex-network:
    driver: bridge
