server:
  port: 8080
spring:
  h2:
    console:
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    hikari:
      connection-test-query: select 1 from dual
      minimum-idle: 1
      maximum-pool-size: 5
    jdbcUrl: jdbc:h2:mem:adex
    username: sa
    password: 12345